export const SET_VIEW_CONFIG = 'SET_VIEW_CONFIG'

// 获取用户信息
export const TASKS_WANGZHUAN_USER_INFO_REQUEST = 'TASKS_WANGZHUAN_USER_INFO_REQUEST';
export const TASKS_WANGZHUAN_USER_INFO_SUCCESS = 'TASKS_WANGZHUAN_USER_INFO_SUCCESS';
export const TASKS_WANGZHUAN_USER_INFO_FAILURE = 'TASKS_WANGZHUAN_USER_INFO_FAILURE';

